[package]
authors = { workspace = true }
description = "fedimint-usdt-tests contains boot integration tests for the usdt module"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-usdt-tests"
publish = false
version = { workspace = true }

[[bin]]
name = "usdt-e2e-test"
path = "bin/usdt_e2e.rs"

[[test]]
name = "fedimint_usdt_tests"
path = "tests/tests.rs"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-mint-common = { workspace = true }
fedimint-mint-server = { workspace = true }
fedimint-mintv2-client = { workspace = true }
fedimint-mintv2-common = { workspace = true }
fedimint-mintv2-server = { workspace = true }
fedimint-server = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-usdt-client = { workspace = true }
fedimint-usdt-common = { workspace = true }
fedimint-usdt-server = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
